# Generated by Django 3.2.6 on 2021-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=35, verbose_name='Штрихкод')),
                ('shop', models.CharField(max_length=100, verbose_name='Магазин')),
                ('shopadress', models.TextField(verbose_name='Адрес магазина')),
                ('shopphone', models.CharField(max_length=50, verbose_name='Телефон магазина')),
                ('sku', models.CharField(max_length=100, verbose_name='Номенклатура')),
                ('specification', models.CharField(max_length=100, verbose_name='Характеристика')),
                ('artikul', models.CharField(max_length=50, verbose_name='Артикул')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
